@inlinable func isPunctuation(code: UInt32) -> Bool {
	switch code {
	case UInt32(EXCLAMATION_CODE), UInt32(QUOTE_DOUBLE_CODE), UInt32(HASH_CODE), 0x24, 0x25, UInt32(AMPERSAND_CODE), UInt32(QUOTE_SINGLE_CODE), UInt32(PAREN_OPEN_CODE), UInt32(PAREN_CLOSE_CODE), UInt32(ASTERISK_CODE), UInt32(PLUS_CODE), UInt32(COMMA_CODE), UInt32(DASH_CODE), UInt32(DOT_CODE), UInt32(SLASH_CODE),
	     UInt32(COLON_CODE), UInt32(SEMICOLON_CODE), UInt32(ANGLE_LEFT_CODE), UInt32(EQUALS_CODE), UInt32(ANGLE_RIGHT_CODE), UInt32(QUESTION_MARK_CODE), UInt32(AT_SIGN_CODE),
	     UInt32(BRACKET_OPEN_CODE), UInt32(BACKSLASH_CODE), UInt32(BRACKET_CLOSE_CODE), UInt32(CARET_CODE), UInt32(UNDERSCORE_CODE), UInt32(BACKTICK_CODE) /* ` */,
	     UInt32(BRACE_LEFT_CODE), UInt32(PIPE_CODE), UInt32(BRACE_RIGHT_CODE), UInt32(TILDE_CODE) /* ~ */:
		return true
	default:
		return false
	}
}
