import Foundation

/// Console/terminal renderers for all node types.

public let consoleRenderers: [Renderer] = [
	consoleAlertRenderer,
	consoleBlockQuoteRenderer,
	consoleCodeBlockRenderer,
	consoleCodeFenceRenderer,
	consoleCodeSpanRenderer,
	consoleCommentRenderer,
	consoleDeletionRenderer,
	consoleEmphasisRenderer,
	consoleFootnoteRenderer,
	consoleFootnoteRefRenderer,
	consoleFootnoteListRenderer,
	consoleHardBreakRenderer,
	consoleHeadingRenderer,
	consoleHeadingUnderlineRenderer,
	consoleHighlightRenderer,
	htmlBlockRenderer,
	htmlSpanRenderer,
	consoleImageRenderer,
	consoleInsertionRenderer,
	consoleLinkRenderer,
	consoleListBulletedRenderer,
	consoleListOrderedRenderer,
	consoleListTaskItemRenderer,
	consoleParagraphRenderer,
	consoleStrikethroughRenderer,
	consoleStrongRenderer,
	consoleTableRenderer,
	consoleTextRenderer,
	consoleThematicBreakRenderer,
]
