import Foundation

/// HTML renderers for all node types.

public let htmlRenderers: [Renderer] = [
	alertRenderer,
	blockQuoteRenderer,
	codeBlockRenderer,
	codeFenceRenderer,
	codeSpanRenderer,
	commentRenderer,
	deletionRenderer,
	emphasisRenderer,
	footnoteRenderer,
	footnoteRefRenderer,
	footnoteListRenderer,
	hardBreakRenderer,
	headingRenderer,
	headingUnderlineRenderer,
	highlightRenderer,
	htmlBlockRenderer,
	htmlSpanRenderer,
	imageRenderer,
	insertionRenderer,
	linkRenderer,
	listBulletedRenderer,
	listOrderedRenderer,
	listTaskItemRenderer,
	paragraphRenderer,
	strikethroughRenderer,
	strongRenderer,
	subscriptRenderer,
	superscriptRenderer,
	tableRenderer,
	tableCellRenderer,
	tableHeaderRenderer,
	tableRowRenderer,
	textRenderer,
	thematicBreakRenderer,
]
