import Foundation
import Collections

@MainActor
let htmlRenderers: OrderedDictionary<String, Renderer> = [
	alertRenderer.name: alertRenderer,
	blockQuoteRenderer.name: blockQuoteRenderer,
	codeBlockRenderer.name: codeBlockRenderer,
	codeFenceRenderer.name: codeFenceRenderer,
	codeSpanRenderer.name: codeSpanRenderer,
	commentRenderer.name: commentRenderer,
	deletionRenderer.name: deletionRenderer,
	emphasisRenderer.name: emphasisRenderer,
	footnoteRenderer.name: footnoteRenderer,
	footnoteListRenderer.name: footnoteListRenderer,
	hardBreakRenderer.name: hardBreakRenderer,
	headingRenderer.name: headingRenderer,
	headingUnderlineRenderer.name: headingUnderlineRenderer,
	highlightRenderer.name: highlightRenderer,
	htmlBlockRenderer.name: htmlBlockRenderer,
	htmlSpanRenderer.name: htmlSpanRenderer,
	imageRenderer.name: imageRenderer,
	insertionRenderer.name: insertionRenderer,
	linkRenderer.name: linkRenderer,
	listBulletedRenderer.name: listBulletedRenderer,
	listOrderedRenderer.name: listOrderedRenderer,
	listTaskItemRenderer.name: listTaskItemRenderer,
	paragraphRenderer.name: paragraphRenderer,
	strikethroughRenderer.name: strikethroughRenderer,
	strongRenderer.name: strongRenderer,
	subscriptRenderer.name: subscriptRenderer,
	superscriptRenderer.name: superscriptRenderer,
	tableRenderer.name: tableRenderer,
	tableCellRenderer.name: tableCellRenderer,
	tableHeaderRenderer.name: tableHeaderRenderer,
	tableRowRenderer.name: tableRowRenderer,
	textRenderer.name: textRenderer,
	thematicBreakRenderer.name: thematicBreakRenderer,
]
